spring:
  application:
    name: gestion-compte

server:
  port: 8080
  servlet:
    context-path: /api/comptes

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
jwt:
  secret:
    key: BCSrS94/1hmDn8HdlgGxq80yUiZRQXoSJ+x0UaW6Sv4=

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

  datasource:
    url: jdbc:h2:file:./data/gestion-compte
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
